
let coreyText =
{
    "nouns": [
        "sadness",
        "grief",
        "sorrow",
        "melancholy",
        "despair",
        "misery",
        "unhappiness",
        "woe",
        "heartache",
        "despondency",
        "gloom",
        "mourning",
        "dejection",
        "depression",
        "heartbreak",
        "grief",
        "dismay",
        "anguish",
        "regret",
        "tragedy",
        "pain",
        "dolefulness",
        "heaviness",
        "melancholia",
        "blue",
        "grief-stricken",
        "downheartedness",
        "loneliness",
        "sorrowfulness",
        "funereal",
        "dispiritedness",
        "woefulness",
        "plaintiveness",
        "wistfulness",
        "dismalness",
        "tearfulness",
        "lamentation",
        "hopelessness",
        "despondence",
        "gloominess",
        "heartfelt",
        "forlornness",
        "doleful",
        "torment",
        "pity",
        "affliction",
        "tristfulness",
        "pessimism",
        "regretfulness",
        "Ian",
        "Chad",
        "Sheldon",
        "Meg",
        "Benny",
        "Ashby",
        "Jake",
        "Abe",
        "Colleen",
        "Corey",
        "Cheney",
        "Butters",
        "Picante Alex",
        "Landon",
        "ultrawide monitor",
        "Ian's office",
        "fish closet",
        "snack closet",
        "strawberry mouse",
        "gold wheels",
        "Benny's pink keyboard",
        "spider plant",
        "butter",
        "bread",
        "Justice Works swamp",
        "Maverick",
        "Downtown Justice Works",
        "Bill Gate's keyboard",
        "Chad's desk",
        "Cheney's desk",
        "Ian's desk",
        "Benny's desk",
        "Ashby's desk",
        "Jake's desk",
        "Abe's desk",
        "Colleen's desk",
        "noise canceling headphones",
        "shoe noodles",
        "microwaved shoes"
    ],
    "nouns-nsfw":[
        "Thug daddy nasty"
    ],
    "verbs": [
        "whine",
        "complain",
        "grumble",
        "whimper",
        "moan",
        "whinge",
        "gripe",
        "protest",
        "fuss",
        "snivel",
        "mutter",
        "grouse",
        "murmur",
        "bellyache",
        "nag",
        "kvetch",
        "bemoan",
        "bleat",
        "carp",
        "cry",
        "wail",
        "lament",
        "pout",
        "object",
        "yammer",
        "grizzle",
        "squawk",
        "wheedle",
        "wail",
        "beef",
        "brood",
        "groan",
        "whinny",
        "crab",
        "yowl",
        "fret",
        "whimper",
        "kick up a fuss",
        "naggle",
        "buzz",
        "sound off",
        "clamor",
        "chide"

    ],
    "adjectives": [
        "sad",
        "unhappy",
        "depressed",
        "melancholy",
        "downcast",
        "mournful",
        "heartbroken",
        "despondent",
        "dismal",
        "blue",
        "tearful",
        "sorrowful",
        "gloomy",
        "forlorn",
        "woeful",
        "grief-stricken",
        "somber",
        "disheartened",
        "miserable",
        "crestfallen",
        "dejected",
        "morose",
        "glum",
        "downhearted",
        "grieving",
        "low-spirited",
        "wretched",
        "troubled",
        "distressed",
        "pensive",
        "disconsolate",
        "wistful",
        "lamenting",
        "mournful",
        "plaintive",
        "woebegone",
        "sullen",
        "heartsick",
        "bummed",
        "weeping",
        "desolate",
        "hopeless",
        "regretful",
        "funereal",
        "doleful",
        "weary",
        "sorry",
        "anguished",
        "heavyhearted"
    ],

    "pronouns": [
        "I",
        "you",
        "he",
        "she",
        "it",
        "we",
        "they",
        "me",
        "you",
        "him",
        "her",
        "it",
        "us",
        "them",
        "my",
        "your",
        "his",
        "her",
        "its",
        "our",
        "their",
        "mine",
        "yours",
        "hers",
        "ours",
        "theirs",
        "this",
        "that",
        "these",
        "those",
        "who",
        "whom",
        "whose",
        "what",
        "which",
        "where",
        "when",
        "why",
        "how",
        "here",
        "there",
        "anybody",
        "anyone",
        "anything",
        "each",
        "either",
        "everybody",
        "everyone",
        "everything",
        "neither",
        "nobody",
        "none",
        "nothing",
        "one",
        "other",
        "others",
        "somebody",
        "someone",
        "something",
        "both",
        "few",
        "many",
        "several",
        "all",
        "any",
        "more",
        "most",
        "none",
        "some",
        "such",
        "enough",
        "little",
        "much",
        "myself",
        "yourself",
        "himself",
        "herself",
        "itself",
        "ourselves",
        "yourselves",
        "themselves",
        "one another",
        "each other",
        "one's self",
        "oneself",
        "myself",
        "yourself",
        "himself",
        "herself",
        "itself",
        "ourselves",
        "yourselves",
        "themselves",
        "one another",
        "each other",
        "one's self",
        "oneself",
        "myself",
        "yourself",
        "himself",
        "herself",
        "itself",
        "ourselves",
        "yourselves",
        "themselves",
        "one another",
        "each other",
        "one's self",
        "oneself"

    ],
    "prepositions": [
        "about",
        "above",
        "across",
        "after",
        "against",
        "along",
        "among",
        "around",
        "at",
        "before",
        "behind",
        "below",
        "beneath",
        "beside",
        "between",
        "beyond",
        "but",
        "by",
        "despite",
        "down",
        "during",
        "except",
        "for",
        "from",
        "in",
        "inside",
        "into",
        "like",
        "near",
        "of",
        "off",
        "on",
        "onto",
        "out",
        "outside",
        "over",
        "past",
        "since",
        "through",
        "throughout",
        "till",
        "to",
        "toward",
        "under",
        "underneath",
        "until",
        "up",
        "upon",
        "with",
        "within",
        "without"
    ],

    "conjunctions": [
        "and",
        "but",
        "or",
        "yet",
        "so",
        "for",
        "nor",
        "after",
        "although",
        "as",
        "because",
        "before",
        "even if",
        "even though",
        "if",
        "in order that",
        "now that",
        "once",
        "since",
        "so that",
        "than",
        "that",
        "though",
        "till",
        "unless",
        "until",
        "when",
        "whenever",
        "where",
        "wherever",
        "whether",
        "while",
        "as",
        "because",
        "before",
        "even if",
        "for example",
        "for this purpose"
    ],

    "interjections": [
        "wow",
        "oh",
        "oops",
        "yikes",
        "hey",
        "hooray",
        "darn",
        "ugh",
        "phew",
        "ouch",
        "gee",
        "aha",
        "bravo",
        "eek",
        "ah",
        "hmm",
        "alas",
        "oh no",
        "sigh",
        "aw",
        "ugh",
        "oh dear",
        "woe",
        "boo hoo",
        "sob",
        "ah",
        "tsk",
        "oh",
        "oh my",
        "dear me",
        "ugh",
        "oh well",
        "oh man",
        "poor me",
        "mercy",
        "tut",
        "drat",
        "woe is me",
        "oh bother",
        "ah me",
        "oh woe",
        "oh boy",
        "jeez",
        "oh lord",
        "oh heavens"
    ],

    "determiners": [
        "the",
        "a",
        "an",
        "this",
        "that",
        "these",
        "those",
        "my",
        "your",
        "his",
        "her",
        "its",
        "our",
        "their",
        "some",
        "any",
        "each",
        "every",
        "all",
        "no",
        "neither",
        "either",
        "both",
        "several",
        "many",
        "few",
        "more",
        "most",
        "much",
        "little"
    ],

    "corey": [
        "works on my machine",
        "Ian did 80 percent",
        "told me to do it",
        "Cheney worked on it first",
        "Chad taught me wrong",
        "I was told they wanted it",
        "Benny did it",
        "not my fault",
        "probably your fault",
        "just do what I’m told",
        "didn’t have enough time",
        "fault",
        "blame",
        "literally copied from Chad",
        "excuses",
        "just started blasting",
        "got dunked on",
        "I’m better at sql",
        "someone else wrote it",
        "your fault",
        "what did i do",
        "didn’t do anything wrong",
        "looked fine when I had it",
        "complaint",
        "attribution",
        "accusation",
        "bitters",
        "it’s too cold outside",
        "copy paste",
        "moldy bread",
        "toilet brush",
        "Megan Fox",
        "parking close to Ian",
        "oh bother",
        "Sneldon",
        "fix butters mistake",
        "fire Benny",
        "fired",
        "Ian buy me more monitors",
        "Ian buy me a new computer",
        "Rocket League",
        "demo Benny",
        "demo Ian",
        "demo Butters",
        "Mo Bettah's",
        "Taco Bell",
        "Empire Chinese",
        "Subway",
        "CSS queen",
        "Sheldon fired me",
        "didn't invite Ian to lunch",
        "gushers",
        "thinks Yoohoo is gross",
        "oh bother",
        "gushers",
        "problem for future Corey",
        "it's probably like that everywhere",
        "Meg",
        "I only walk when it's 72-79 degrees outside",
        "did you try fixing it",
        "Colleen better buy me redbull",
        "everyone's mean to me for no reason",
        "cash me outside",
        "self-inflicted",
        "copy-paste",
        "everlast",
        "eeyore",
        "Benny didn't QC good enough",
        "inculpate",
        "point the finger",
        "i don't know",
        "not me",
        "someone else's fault",
        "blame Cheney",
        "web dev 0.5",
        "princess Benny",
        "taking the family to Chili's",
        "did you try making it work",
        "steal Ashby's wheels",
        "tea time",
        "must be nice",
        "well well well",
        "DSO",
        "Being mean to Ashby in OW",
        "Chad is my team lead",
        "Sounds like a personal problem"
    ],
    "corey-nsfw":[
        "Ian's mom",
        "bagging",
        "tea bag",
        "deez nuts",
        "your mom",
        "14 beers at Chili's",
        "Did your Mom",
        "no pants",
        "last night with your mom"
    ]
    
}
