
let coreyText =
{
    "nouns": [
        "dog",
        "cat",
        "mouse",
        "bird",
        "fish",
        "horse",
        "cow",
        "pig",
        "sheep",
        "goat",
        "chicken",
        "duck",
        "rabbit",
        "frog",
        "lizard",
        "snake",
        "bear",
        "lion",
        "tiger",
        "monkey",
        "elephant",
        "giraffe",
        "zebra",
        "kangaroo",
        "panda",
        "penguin",
        "whale",
        "shark",
        "dolphin",
        "octopus",
        "crab",
        "lobster",
        "spider",
        "ant",
        "bee",
        "butterfly",
        "dragonfly",
        "mosquito",
        "fly",
        "grasshopper",
        "ladybug",
        "car",
        "truck",
        "bus",
        "train",
        "plane",
        "boat",
        "ship",
        "bicycle",
        "motorcycle",
        "scooter",
        "skateboard",
        "wheel",
        "house",
        "apartment",
        "school",
        "hospital",
        "church",
        "library",
        "museum",
        "park",
        "restaurant",
        "store",
        "tree",
        "flower",
        "grass",
        "cloud",
        "sun",
        "moon",
        "star",
        "snowflake",
        "raindrop",
        "snowman",
        "fire",
        "lightning",
        "cloud",
        "rain",
        "snow",
        "wind",
        "water",
        "ocean",
        "lake",
        "river",
        "mountain",
        "hill",
        "rock",
        "sand",
        "soil",
        "sky",
        "grass",
        "tree",
        "flower",
        "leaf",
        "cloud",
        "sun",
        "moon",
        "star",
        "snowflake",
        "raindrop",
        "snowman",
        "fire",
        "lightning",
        "cloud",
        "rain",
        "snow",
        "wind",
        "water",
        "ocean",
        "lake",
        "river",
        "mountain",
        "hill",
        "Ian",
        "Chad",
        "Sheldon",
        "Meg",
        "Benny",
        "Ashby",
        "Jake",
        "Abe"
    ],
    "verbs": [
        "run",
        "jump",
        "swim",
        "fly",
        "walk",
        "crawl",
        "climb",
        "dance",
        "sing",
        "play",
        "read",
        "write",
        "draw",
        "paint",
        "cook",
        "eat",
        "sleep",
        "wake",
        "laugh",
        "cry",
        "talk",
        "listen",
        "watch",
        "look",
        "smell",
        "feel",
        "touch",
        "hear",
        "see",
        "know",
        "think",
        "believe",
        "understand",
        "remember",
        "forget",
        "want",
        "need",
        "like",
        "love",
        "hate",
        "hope",
        "wish",
        "dream",
        "believe",
        "know",
        "understand",
        "remember",
        "forget",
        "want",
        "need",
        "like",
        "love",
        "hate",
        "hope",
        "wish",
        "dream",
        "believe",
        "know",
        "understand",
        "remember",
        "forget",
        "want",
        "need",
        "like",
        "love",
        "hate",
        "hope",
        "wish",
        "dream",
        "believe",
        "know",
        "understand",
        "remember",
        "forget",
        "want",
        "need",
        "like",
        "love",
        "hate",
        "hope",
        "wish",
        "dream",
        "believe",
        "know",
        "understand",
        "remember",
        "forget",
        "want",
        "need",
        "like",
        "love",
        "hate",
        "hope",
        "wish",
        "dream",
        "believe",
        "know",
        "understand",
        "remember",
        "forget",
        "want",
        "need",
        "like",
        "love",
        "hate",
        "hope",
        "wish",
        "dream",
        "believe",
        "know",
        "understand",
        "remember",
        "forget",
        "want",
        "need",
        "like",
        "love",
        "hate"
        
    ],
    "adjectives": [
        "big",
        "small",
        "tall",
        "short",
        "long",
        "fat",
        "thin",
        "round",
        "square",
        "cold",
        "hot",
        "warm",
        "cool",
        "dry",
        "wet",
        "fast",
        "slow",
        "hard",
        "soft",
        "heavy",
        "light",
        "strong",
        "weak",
        "clean",
        "dirty",
        "new",
        "old",
        "good",
        "bad",
        "happy",
        "sad",
        "funny",
        "boring",
        "nice",
        "mean",
        "friendly",
        "unfriendly",
        "polite",
        "rude",
        "quiet",
        "loud"
        
    ],

    "pronouns": [
        "I",
        "you",
        "he",
        "she",
        "it",
        "we",
        "they",
        "me",
        "you",
        "him",
        "her",
        "it",
        "us",
        "them",
        "my",
        "your",
        "his",
        "her",
        "its",
        "our",
        "their",
        "mine",
        "yours",
        "hers",
        "ours",
        "theirs",
        "this",
        "that",
        "these",
        "those",
        "who",
        "whom",
        "whose",
        "what",
        "which",
        "where",
        "when",
        "why",
        "how",
        "here",
        "there",
        "anybody",
        "anyone",
        "anything",
        "each",
        "either",
        "everybody",
        "everyone",
        "everything",
        "neither",
        "nobody",
        "none",
        "nothing",
        "one",
        "other",
        "others",
        "somebody",
        "someone",
        "something",
        "both",
        "few",
        "many",
        "several",
        "all",
        "any",
        "more",
        "most",
        "none",
        "some",
        "such",
        "enough",
        "little",
        "much",
        "myself",
        "yourself",
        "himself",
        "herself",
        "itself",
        "ourselves",
        "yourselves",
        "themselves",
        "one another",
        "each other",
        "one's self",
        "oneself",
        "myself",
        "yourself",
        "himself",
        "herself",
        "itself",
        "ourselves",
        "yourselves",
        "themselves",
        "one another",
        "each other",
        "one's self",
        "oneself",
        "myself",
        "yourself",
        "himself",
        "herself",
        "itself",
        "ourselves",
        "yourselves",
        "themselves",
        "one another",
        "each other",
        "one's self",
        "oneself"
        
    ],
    "prepositions": [
        "about",
        "above",
        "across",
        "after",
        "against",
        "along",
        "among",
        "around",
        "at",
        "before",
        "behind",
        "below",
        "beneath",
        "beside",
        "between",
        "beyond",
        "but",
        "by",
        "despite",
        "down",
        "during",
        "except",
        "for",
        "from",
        "in",
        "inside",
        "into",
        "like",
        "near",
        "of",
        "off",
        "on",
        "onto",
        "out",
        "outside",
        "over",
        "past",
        "since",
        "through",
        "throughout",
        "till",
        "to",
        "toward",
        "under",
        "underneath",
        "until",
        "up",
        "upon",
        "with",
        "within",
        "without"
    ],

    "conjunctions": [
        "and",
        "but",
        "or",
        "yet",
        "so",
        "for",
        "nor",
        "after",
        "although",
        "as",
        "because",
        "before",
        "even if",
        "even though",
        "if",
        "in order that",
        "now that",
        "once",
        "since",
        "so that",
        "than",
        "that",
        "though",
        "till",
        "unless",
        "until",
        "when",
        "whenever",
        "where",
        "wherever",
        "whether",
        "while",
        "as",
        "because",
        "before",
        "even if",
        "for example",
        "for this purpose"
    ],
        
    "corey": [    
        "works on my machine",
        "Ian did 80 percent",
        "told me to do it",
        "Cheney worked on it first",
        "Chad taught me wrong",
        "I was told they wanted it",
        "Benny did it",
        "not my fault",
        "probably your fault",
        "just do what I’m told",
        "didn’t have enough time",
        "fault",
        "blame",
        "literally copied from chad",
        "excuses",
        "just started blasting",
        "got dunked on",
        "I’m better at sql",
        "someone else wrote it",
        "your fault",
        "what did i do",
        "didn’t do anything wrong",
        "looked fine when I had it",
        "complaint",
        "attribution",
        "accusation",
        "your mom",
        "bitters",
        "it’s too cold outside",
        "copy paste",
        "moldy bread",
        "toilet brush",
        "deez nuts",
        "Megan Fox",
        "parking close to Ian",
        "oh bother",
        "Sneldon",
        "fix butters mistake",
        "fire Benny",
        "fired",
        "Ian buy me more monitors",
        "Ian buy me a new computer",
        "Rocket League",
        "demo Benny",
        "demo Ian",
        "demo Butters",
        "Mo Bettah's",
        "Taco Bell",
        "Empire Chinese",
        "Subway",
        "CSS queen",
        "Sheldon fired me",
        "didn't invite Ian to lunch",
        "gushers",
        "thinks Yoohoo is gross",
        "oh bother",
        "gushers",
        "problem for future Corey",
        "it's probably like that everywhere",
        "Ian's mom",
        "Meg",
        "I only walk when it's 72-79 degrees outside"
        ]
}


